# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74eff0c9e67e0301c482c33c647d14a98b66331ecf691e700bbd3388f1f7354f095772ba15fb28a2f8cd4666c4feb0ddb16325893e37c257793bcf3187779171

test:
  secret_key_base: 1481ae6fabf4266b853b65c2d2f1f48d600d82d9f2399fa4ecace270fa6fae3569fa8ff8586645c997774da13dbb53682bcb4673beee815d7fe60c628e639463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
